export const home = {
    id: 'home',
    title: 'HOME',
    href: '/admin/monitoring/dashboard',
    linkAs: '/admin/monitoring/dashboard',
    isVisible: true,
    isLocked: false,
};

export const menuLists = [
    {
        id: 'site-management',
        title: 'Site Management',
        href: '',
        linkAs: '',
        isVisible: true,
        isLocked: false,
        children: [
            {
                id: 'monitoring_dashboard',
                title: 'Notifications',
                href: '/admin/site/notifications',
                linkAs: '/admin/site/notifications',
                isVisible: true,
                isLocked: false,
            },
        ],
    },
    {
        id: 'demo',
        title: 'Demo',
        href: '',
        linkAs: '',
        isVisible: true,
        isLocked: false,
        children: [
            {
                id: 'blank',
                title: 'Blank Page',
                href: '/demo/blank_page',
                linkAs: '/demo/blank_page',
                isVisible: true,
                isLocked: false,
            },
            {
                id: 'chart',
                title: 'Chart',
                href: '/demo/chart',
                linkAs: '/demo/chart',
                isVisible: true,
                isLocked: false,
            },
            {
                id: 'table',
                title: 'Table',
                href: '/demo/table',
                linkAs: '/demo/table',
                isVisible: true,
                isLocked: false,
            },
            {
                id: 'data-flow',
                title: 'Data Flow',
                href: '/demo/data-flow',
                linkAs: '/demo/data-flow',
                isVisible: true,
                isLocked: false,
            },
            {
                id: 'feedback',
                title: 'Feedback',
                href: '/demo/feedback',
                linkAs: '/demo/feedback',
                isVisible: true,
                isLocked: false,
            },
            {
                id: 'ui',
                title: 'UI',
                href: '/demo/ui',
                linkAs: '/demo/ui',
                isVisible: true,
                isLocked: false,
            },
            {
                id: 'form',
                title: 'Form',
                href: '/demo/form',
                linkAs: '/demo/form',
                isVisible: true,
                isLocked: false,
            },
            {
                id: 'search',
                title: 'Search',
                href: '/demo/search',
                linkAs: '/demo/search',
                isVisible: true,
                isLocked: false,
            },
        ],
    },
    {
        id: 'search',
        title: 'Search',
        href: '/demo/search',
        linkAs: '/demo/search',
        isVisible: true,
        isLocked: false,
    },
    {
        id: 'permission',
        title: 'Permission',
        href: '',
        linkAs: '',
        isVisible: true,
        isLocked: false,
        children: [
            {
                id: 'permission_index',
                title: 'List',
                href: '/_admin/auth',
                linkAs: '/_admin/auth',
                isVisible: true,
                isLocked: false,
            },
        ],
    },
];
